[project]
name = "deeplearningbook"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.5.3",
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "scipy>=1.17.0",
    "scipy-stubs~=1.17.0",
    "torch>=2.10.0",
]
